version: '3.0'

services:
  grafana:
    container_name: 'openc3-cosmos-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.5.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/openc3-cosmos-datasource
      - ./provisioning:/etc/grafana/provisioning
